### ISSUE TITLE
Add subpaths for each configured check

### ISSUE THREAD

**Issue by theunraveler** [packethost/healthcheck-rb#2]
In addition to answering at the main configured endpoint, there should also be endpoints to allow you to drill down into each check. Something like `GET /healthcheck/:check`.

**Comment by betawaffle** [comment]
Hmm, that's a good idea.

**Comment by theunraveler** [comment]
Closed first by https://github.com/packethost/healthcheck-rb/commit/289d172ad149e68312a3252c58908a2770015bc3, then better by https://github.com/packethost/healthcheck-rb/commit/74d30b423606c9bc488bd67e5d2684db70996d9a.
